name: Capture GitHub Profile Screenshot

on:
  issues:
    types: [opened]

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npm install puppeteer
          npx puppeteer browsers install chrome

      - name: Capture Screenshot
        run: node .github/workflows/capture-screenshot.js ${{ github.event.issue.user.login }}

      - name: Commit and Push Screenshot
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add screenshots/
          git commit -m "Add screenshot for ${{ github.event.issue.user.login }}"
          git push
